/*
 * the sql script to create table "MyBackup" and "MyLog"
 */
/*
create table MyBackup (
	ID integer identity primary key,
	BINARY_DATA blob not null, 
	BACKUP_DATE date not null,
	BACKUP_USER varchar(20) not null
)

create table MyLog ( 
	ID integer identity primary key,
	LOG_CONTENT varchar(200),
	LOG_DATE date not null,
	LOG_USER varchar(20) not null
)
*/

/*
 * database checking sql script start here ~
 */
select *
from MyLog
where 1=1
;

select id, backup_date, backup_user
from MyBackup
where 1=1
;

-- the tool doesn't support to display blob data...
select binary_data 
from MyBackup
;

/*
 * remove the testing data in table 
 */
/*
delete from MyBackup
where 1=1
;

delete from MyLog
where 1=1
;
*/

/*
	[note] the syntax of the autoincrement of the primary key...

	id INTEGER IDENTITY PRIMARY KEY,
	pattern: <column label> integer identity primary key,
	
	id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 100, INCREMENT BY 1) PRIMARY KEY,
	pattern: <column label> integer generated by default as identity(start with <start value>, increment by <iterate value>) primary key,
*/

